/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: thesidekick (https://sketchfab.com/thesidekick)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/banana-dda3a1f707a94c52bed79578e120937c
title: Banana
*/

import ReactDOM from "react-dom";
import { Suspense, lazy, useState } from "react";
import "./index.css";
import Overlay from "./layout/Overlay";
import { FadeIn, LeftMiddle } from "./layout/styles";

// import Bananas from "./Bananas";
// Comment the above and uncomment the following to import the WebGL BG lazily for faster loading times
const Bananas = lazy(() => import("./Bananas"));

export default function App() {
  const [speed, set] = useState(1);
  return (
    <>
      <Suspense fallback={null}>
        <Bananas speed={speed} />
        <FadeIn />
      </Suspense>
      <Overlay />
    </>
  );
}
